apiVersion: v1
kind: Service
metadata:
    name: "dsmsk8s"
    labels:
        app: "dsmsk8s"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "dsmsk8s"