on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: desattiacr.azurecr.io
        username: ${{ secrets.acr_desattiacr_username }}
        password: ${{ secrets.acr_desattiacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t desattiacr.azurecr.io/dsmsk8s:${{ github.sha }}
        docker push desattiacr.azurecr.io/dsmsk8s:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_dsmsk8s_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dsmsk8s6ccf | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dsmsk8s6ccf`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dsmsk8s6ccf
        container-registry-url: desattiacr.azurecr.io
        container-registry-username: ${{ secrets.acr_desattiacr_username }}
        container-registry-password: ${{ secrets.acr_desattiacr_password }}
        secret-name: dsmsk8sdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: dsmsk8s6ccf
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          desattiacr.azurecr.io/dsmsk8s:${{ github.sha }}
        imagepullsecrets: |
          dsmsk8sdockerauth